
// This file has been generated by the GUI designer. Do not modify.
namespace Tutor.UserInterface
{
	public partial class LoadErrorPane
	{
		private global::Gtk.Label ErrorPane;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Tutor.UserInterface.LoadErrorPane
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Tutor.UserInterface.LoadErrorPane";
			// Container child Tutor.UserInterface.LoadErrorPane.Gtk.Container+ContainerChild
			this.ErrorPane = new global::Gtk.Label ();
			this.ErrorPane.Name = "ErrorPane";
			this.ErrorPane.LabelProp = global::Mono.Unix.Catalog.GetString ("Error");
			this.ErrorPane.Justify = ((global::Gtk.Justification)(2));
			this.Add (this.ErrorPane);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
