
// This file has been generated by the GUI designer. Do not modify.
namespace TutorLevels
{
	public partial class LevelBox
	{
		private global::Gtk.Label label1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TutorLevels.LevelBox
			global::Stetic.BinContainer.Attach (this);
			this.Name = "TutorLevels.LevelBox";
			// Container child TutorLevels.LevelBox.Gtk.Container+ContainerChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.Add (this.label1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
